"""PayPal 账单地址池（ASCII 安全，避免德文编码污染）。"""

US_BILLING_NAMES = [
    ("James", "Smith"),
    ("John", "Brown"),
    ("Michael", "Johnson"),
    ("Robert", "Miller"),
    ("David", "Davis"),
    ("William", "Wilson"),
    ("Richard", "Moore"),
    ("Joseph", "Taylor"),
    ("Thomas", "Anderson"),
    ("Charles", "Thomas"),
    ("Christopher", "Jackson"),
    ("Daniel", "White"),
    ("Matthew", "Harris"),
    ("Anthony", "Martin"),
    ("Mark", "Thompson"),
    ("Donald", "Garcia"),
    ("Steven", "Martinez"),
    ("Paul", "Robinson"),
    ("Andrew", "Clark"),
    ("Joshua", "Rodriguez"),
    ("Kenneth", "Lewis"),
    ("Kevin", "Lee"),
    ("Brian", "Walker"),
    ("George", "Hall"),
    ("Timothy", "Allen"),
    ("Ronald", "Young"),
    ("Jason", "Hernandez"),
    ("Edward", "King"),
    ("Jeffrey", "Wright"),
    ("Ryan", "Lopez"),
    ("Jacob", "Hill"),
    ("Gary", "Scott"),
    ("Nicholas", "Green"),
    ("Eric", "Adams"),
    ("Jonathan", "Baker"),
    ("Stephen", "Nelson"),
    ("Larry", "Carter"),
    ("Justin", "Mitchell"),
    ("Scott", "Perez"),
    ("Brandon", "Roberts"),
    ("Samuel", "Turner"),
    ("Benjamin", "Phillips"),
    ("Raymond", "Campbell"),
    ("Gregory", "Parker"),
    ("Frank", "Evans"),
    ("Alexander", "Edwards"),
    ("Patrick", "Collins"),
    ("Jack", "Stewart"),
    ("Dennis", "Sanchez"),
    ("Jerry", "Morris"),
    ("Tyler", "Rogers"),
    ("Aaron", "Reed"),
    ("Jose", "Cook"),
    ("Adam", "Morgan"),
    ("Henry", "Bell"),
    ("Nathan", "Murphy"),
    ("Douglas", "Bailey"),
    ("Zachary", "Rivera"),
    ("Peter", "Cooper"),
    ("Kyle", "Richardson"),
    ("Walter", "Cox"),
    ("Ethan", "Howard"),
    ("Jeremy", "Ward"),
    ("Harold", "Torres"),
    ("Carl", "Peterson"),
    ("Keith", "Gray"),
    ("Roger", "Ramirez"),
    ("Gerald", "James"),
    ("Christian", "Watson"),
]

US_BILLING_STREETS = [
    ("1600 Amphitheatre Parkway", "Mountain View", "CA", "94043"),
    ("1 Infinite Loop", "Cupertino", "CA", "95014"),
    ("350 Fifth Avenue", "New York", "NY", "10118"),
    ("233 S Wacker Drive", "Chicago", "IL", "60606"),
    ("600 Congress Avenue", "Austin", "TX", "78701"),
    ("1000 Louisiana Street", "Houston", "TX", "77002"),
    ("191 Peachtree Street NE", "Atlanta", "GA", "30303"),
    ("2001 Ross Avenue", "Dallas", "TX", "75201"),
    ("1 Boston Place", "Boston", "MA", "02108"),
    ("1500 Market Street", "Philadelphia", "PA", "19102"),
    ("1201 Third Avenue", "Seattle", "WA", "98101"),
    ("1801 California Street", "Denver", "CO", "80202"),
    ("201 North Central Avenue", "Phoenix", "AZ", "85004"),
    ("100 North Tampa Street", "Tampa", "FL", "33602"),
    ("201 South Biscayne Boulevard", "Miami", "FL", "33131"),
    ("50 West Liberty Street", "Reno", "NV", "89501"),
    ("400 South Hope Street", "Los Angeles", "CA", "90071"),
    ("555 California Street", "San Francisco", "CA", "94104"),
    ("707 Wilshire Boulevard", "Los Angeles", "CA", "90017"),
    ("1999 Broadway", "Oakland", "CA", "94612"),
    ("1100 Peachtree Street", "Atlanta", "GA", "30309"),
    ("500 Grant Street", "Pittsburgh", "PA", "15219"),
    ("200 Public Square", "Cleveland", "OH", "44114"),
    ("1 North Dearborn Street", "Chicago", "IL", "60602"),
    ("225 Franklin Street", "Boston", "MA", "02110"),
    ("101 Constitution Avenue NW", "Washington", "DC", "20001"),
    ("1200 19th Street NW", "Washington", "DC", "20036"),
    ("300 South Grand Avenue", "Los Angeles", "CA", "90071"),
    ("875 North Michigan Avenue", "Chicago", "IL", "60611"),
    ("2500 North Lakeview Avenue", "Chicago", "IL", "60614"),
    ("1400 Smith Street", "Houston", "TX", "77002"),
    ("301 Congress Avenue", "Austin", "TX", "78701"),
    ("1221 Avenue of the Americas", "New York", "NY", "10020"),
    ("375 Hudson Street", "New York", "NY", "10014"),
    ("4 World Trade Center", "New York", "NY", "10007"),
    ("1 Penn Plaza", "New York", "NY", "10119"),
    ("1313 Disneyland Drive", "Anaheim", "CA", "92802"),
    ("800 Boylston Street", "Boston", "MA", "02199"),
    ("2001 Clayton Road", "Concord", "CA", "94520"),
    ("4100 North Scottsdale Road", "Scottsdale", "AZ", "85251"),
    ("1001 Fannin Street", "Houston", "TX", "77002"),
    ("2211 North First Street", "San Jose", "CA", "95131"),
    ("410 Terry Avenue North", "Seattle", "WA", "98109"),
    ("500 West 2nd Street", "Austin", "TX", "78701"),
    ("1 Hacker Way", "Menlo Park", "CA", "94025"),
    ("1355 Market Street", "San Francisco", "CA", "94103"),
    ("888 Brannan Street", "San Francisco", "CA", "94103"),
    ("1455 Market Street", "San Francisco", "CA", "94103"),
    ("717 Olympic Boulevard", "Santa Monica", "CA", "90404"),
    ("2045 W Grand Avenue", "Chicago", "IL", "60612"),
    ("2333 N Michigan Avenue", "Chicago", "IL", "60601"),
    ("875 N Michigan Avenue", "Chicago", "IL", "60611"),
    ("11 Times Square", "New York", "NY", "10036"),
    ("1271 Avenue of the Americas", "New York", "NY", "10020"),
    ("299 Park Avenue", "New York", "NY", "10171"),
    ("200 Vesey Street", "New York", "NY", "10281"),
    ("1 Liberty Plaza", "New York", "NY", "10006"),
    ("90 Hudson Street", "Jersey City", "NJ", "07302"),
    ("101 Crawfords Corner Road", "Holmdel", "NJ", "07733"),
    ("1 Microsoft Way", "Redmond", "WA", "98052"),
    ("1020 102nd Avenue NE", "Bellevue", "WA", "98004"),
    ("500 E Pratt Street", "Baltimore", "MD", "21202"),
    ("100 Light Street", "Baltimore", "MD", "21202"),
    ("1500 E Main Street", "Richmond", "VA", "23219"),
    ("1000 E Paris Avenue SE", "Grand Rapids", "MI", "49546"),
    ("1 Woodward Avenue", "Detroit", "MI", "48226"),
    ("201 E 6th Street", "Cincinnati", "OH", "45202"),
    ("127 Public Square", "Cleveland", "OH", "44114"),
    ("201 S Tryon Street", "Charlotte", "NC", "28202"),
    ("100 North Main Street", "Memphis", "TN", "38103"),
    ("4141 Hacienda Drive", "Pleasanton", "CA", "94588"),
    ("6801 Rockledge Drive", "Bethesda", "MD", "20817"),
    ("1 CVS Drive", "Woonsocket", "RI", "02895"),
    ("1 Patriot Place", "Foxborough", "MA", "02035"),
    ("1 Post Street", "San Francisco", "CA", "94104"),
    ("6000 American Parkway", "Madison", "WI", "53783"),
    ("1 John Deere Place", "Moline", "IL", "61265"),
    ("1 Coca-Cola Plaza", "Atlanta", "GA", "30313"),
    ("1 Busch Place", "St Louis", "MO", "63118"),
    ("1 Prudential Plaza", "Chicago", "IL", "60601"),
    ("2000 Post Oak Boulevard", "Houston", "TX", "77056"),
    ("1901 Avenue of the Stars", "Los Angeles", "CA", "90067"),
    ("10250 Constellation Boulevard", "Los Angeles", "CA", "90067"),
    ("3333 Beverly Road", "Hoffman Estates", "IL", "60179"),
    ("700 Anderson Hill Road", "Purchase", "NY", "10577"),
    ("1 American Lane", "Greenwich", "CT", "06831"),
    ("1 Financial Plaza", "Fort Lauderdale", "FL", "33394"),
    ("801 Brickell Avenue", "Miami", "FL", "33131"),
    ("601 Poydras Street", "New Orleans", "LA", "70130"),
    ("1201 Lake Robbins Drive", "The Woodlands", "TX", "77380"),
    ("1 Dell Way", "Round Rock", "TX", "78682"),
    ("2300 Traverwood Drive", "Ann Arbor", "MI", "48105"),
    ("1 Bowerman Drive", "Beaverton", "OR", "97005"),
    ("1 NW 161st Avenue", "Pembroke Pines", "FL", "33028"),
    ("500 South Buena Vista Street", "Burbank", "CA", "91521"),
    ("2900 W Alameda Avenue", "Burbank", "CA", "91505"),
]

DE_BILLING_NAMES = [
    ("Lukas", "Mueller"),
    ("Anna", "Schmidt"),
    ("Felix", "Weber"),
    ("Sophie", "Fischer"),
    ("Jonas", "Becker"),
    ("Emma", "Wagner"),
    ("Leon", "Schulz"),
    ("Mia", "Hoffmann"),
    ("Paul", "Koch"),
    ("Hannah", "Richter"),
    ("Maximilian", "Klein"),
    ("Lena", "Wolf"),
    ("Tim", "Schroeder"),
    ("Laura", "Neumann"),
    ("Niklas", "Schwarz"),
    ("Julia", "Zimmermann"),
    ("David", "Braun"),
    ("Sarah", "Krueger"),
    ("Finn", "Hartmann"),
    ("Marie", "Lange"),
    ("Elias", "Werner"),
    ("Clara", "Schmitt"),
    ("Ben", "Krause"),
    ("Lea", "Meier"),
    ("Noah", "Lehmann"),
    ("Luisa", "Huber"),
    ("Tom", "Kaiser"),
    ("Nina", "Fuchs"),
    ("Moritz", "Peters"),
    ("Katharina", "Lang"),
    ("Jan", "Scholz"),
    ("Sven", "Vogel"),
    ("Stefan", "Friedrich"),
    ("Andreas", "Guenther"),
    ("Markus", "Keller"),
    ("Sabine", "Herrmann"),
    ("Petra", "Koenig"),
    ("Thomas", "Walter"),
    ("Michael", "Mayer"),
    ("Daniel", "Berger"),
    ("Christina", "Boehm"),
    ("Florian", "Franke"),
    ("Vanessa", "Albrecht"),
    ("Tobias", "Simon"),
    ("Melanie", "Ludwig"),
    ("Sebastian", "Winter"),
    ("Kathrin", "Kraus"),
    ("Oliver", "Vogt"),
    ("Jessica", "Jung"),
    ("Patrick", "Kuhn"),
    ("Nicole", "Arnold"),
    ("Christian", "Busch"),
    ("Sandra", "Engel"),
    ("Martin", "Otto"),
    ("Jennifer", "Paul"),
    ("Alexander", "Horn"),
    ("Stefanie", "Arnold"),
    ("Matthias", "Berg"),
    ("Anja", "Pohl"),
    ("Ralf", "Sauer"),
    ("Birgit", "Kraft"),
    ("Holger", "Brandt"),
    ("Monika", "Voigt"),
    ("Uwe", "Graf"),
    ("Heike", "Dietrich"),
    ("Joerg", "Kuhn"),
    ("Silke", "Bachmann"),
    ("Rainer", "Seidel"),
    ("Cornelia", "Heinrich"),
]

DE_BILLING_STREETS = [
    ("Friedrichstrasse 123", "Berlin", "Berlin", "10117"),
    ("Unter den Linden 77", "Berlin", "Berlin", "10117"),
    ("Alexanderplatz 1", "Berlin", "Berlin", "10178"),
    ("Kurfuerstendamm 194", "Berlin", "Berlin", "10707"),
    ("Marienplatz 8", "Muenchen", "Bayern", "80331"),
    ("Leopoldstrasse 50", "Muenchen", "Bayern", "80802"),
    ("Sendlinger Strasse 44", "Muenchen", "Bayern", "80331"),
    ("Zeil 85", "Frankfurt", "Hessen", "60313"),
    ("Mainzer Landstrasse 250", "Frankfurt", "Hessen", "60327"),
    ("Neuer Wall 50", "Hamburg", "Hamburg", "20354"),
    ("Reeperbahn 1", "Hamburg", "Hamburg", "20359"),
    ("Jungfernstieg 16", "Hamburg", "Hamburg", "20354"),
    ("Koenigsallee 60", "Duesseldorf", "Nordrhein-Westfalen", "40212"),
    ("Koenigsstrasse 1", "Stuttgart", "Baden-Wuerttemberg", "70173"),
    ("Koenigstrasse 28", "Stuttgart", "Baden-Wuerttemberg", "70173"),
    ("Markt 1", "Koeln", "Nordrhein-Westfalen", "50667"),
    ("Hohe Strasse 68", "Koeln", "Nordrhein-Westfalen", "50667"),
    ("Koenigstrasse 1", "Dresden", "Sachsen", "01097"),
    ("Prager Strasse 12", "Dresden", "Sachsen", "01069"),
    ("Grimmaische Strasse 2", "Leipzig", "Sachsen", "04109"),
    ("Nikolaistrasse 1", "Leipzig", "Sachsen", "04109"),
    ("Koenigstrasse 1", "Nuernberg", "Bayern", "90402"),
    ("Karolinenstrasse 35", "Nuernberg", "Bayern", "90402"),
    ("Koenigstrasse 1", "Hannover", "Niedersachsen", "30159"),
    ("Georgstrasse 36", "Hannover", "Niedersachsen", "30159"),
    ("Koenigstrasse 1", "Bremen", "Bremen", "28195"),
    ("Obernstrasse 1", "Bremen", "Bremen", "28195"),
    ("Koenigstrasse 1", "Mannheim", "Baden-Wuerttemberg", "68159"),
    ("Planken 1", "Mannheim", "Baden-Wuerttemberg", "68161"),
    ("Koenigstrasse 1", "Karlsruhe", "Baden-Wuerttemberg", "76133"),
    ("Kaiserstrasse 233", "Karlsruhe", "Baden-Wuerttemberg", "76133"),
    ("Koenigstrasse 1", "Freiburg", "Baden-Wuerttemberg", "79098"),
    ("Bertoldstrasse 1", "Freiburg", "Baden-Wuerttemberg", "79098"),
    ("Koenigstrasse 1", "Bonn", "Nordrhein-Westfalen", "53111"),
    ("Markt 1", "Bonn", "Nordrhein-Westfalen", "53111"),
    ("Koenigstrasse 1", "Wiesbaden", "Hessen", "65183"),
    ("Wilhelmstrasse 1", "Wiesbaden", "Hessen", "65183"),
    ("Koenigstrasse 1", "Mainz", "Rheinland-Pfalz", "55116"),
    ("Schusterstrasse 1", "Mainz", "Rheinland-Pfalz", "55116"),
    ("Koenigstrasse 1", "Augsburg", "Bayern", "86150"),
    ("Rosenthaler Strasse 40", "Berlin", "Berlin", "10178"),
    ("Potsdamer Platz 1", "Berlin", "Berlin", "10785"),
    ("Hackescher Markt 1", "Berlin", "Berlin", "10178"),
    ("Schlossstrasse 1", "Berlin", "Berlin", "12163"),
    ("Rheinstrasse 1", "Berlin", "Berlin", "12161"),
    ("Maximilianstrasse 15", "Muenchen", "Bayern", "80539"),
    ("Theatinerstrasse 7", "Muenchen", "Bayern", "80333"),
    ("Tal 1", "Muenchen", "Bayern", "80331"),
    ("Rosenheimer Strasse 145", "Muenchen", "Bayern", "81671"),
    ("Hanauer Landstrasse 182", "Frankfurt", "Hessen", "60314"),
    ("Bockenheimer Landstrasse 2", "Frankfurt", "Hessen", "60306"),
    ("Berger Strasse 175", "Frankfurt", "Hessen", "60385"),
    ("Grosse Bleichen 35", "Hamburg", "Hamburg", "20354"),
    ("Ballindamm 25", "Hamburg", "Hamburg", "20095"),
    ("Steinweg 1", "Hamburg", "Hamburg", "20355"),
    ("Schadowstrasse 11", "Duesseldorf", "Nordrhein-Westfalen", "40212"),
    ("Berliner Allee 52", "Duesseldorf", "Nordrhein-Westfalen", "40212"),
    ("Calwer Strasse 21", "Stuttgart", "Baden-Wuerttemberg", "70173"),
    ("Eberhardstrasse 1", "Stuttgart", "Baden-Wuerttemberg", "70173"),
    ("Schildergasse 65", "Koeln", "Nordrhein-Westfalen", "50667"),
    ("Domkloster 4", "Koeln", "Nordrhein-Westfalen", "50667"),
    ("Antonienstrasse 2", "Dresden", "Sachsen", "01097"),
    ("Weberstrasse 1", "Leipzig", "Sachsen", "04109"),
    ("Karl-Liebknecht-Strasse 1", "Leipzig", "Sachsen", "04109"),
    ("Ludwigstrasse 25", "Nuernberg", "Bayern", "90402"),
    ("Bahnhofstrasse 1", "Hannover", "Niedersachsen", "30159"),
    ("Contrescarpe 33", "Bremen", "Bremen", "28195"),
    ("F1 1-2", "Mannheim", "Baden-Wuerttemberg", "68159"),
    ("Kaiserpassage 10", "Karlsruhe", "Baden-Wuerttemberg", "76133"),
    ("Salzstrasse 1", "Freiburg", "Baden-Wuerttemberg", "79098"),
    ("Friedrichstrasse 38", "Bonn", "Nordrhein-Westfalen", "53111"),
    ("Kirchgasse 6", "Wiesbaden", "Hessen", "65183"),
    ("Grosse Langgasse 38", "Mainz", "Rheinland-Pfalz", "55116"),
    ("Maximilianstrasse 1", "Augsburg", "Bayern", "86150"),
    ("Schillerstrasse 1", "Essen", "Nordrhein-Westfalen", "45127"),
    ("Kettwiger Strasse 36", "Essen", "Nordrhein-Westfalen", "45127"),
    ("Koenigstrasse 1", "Dortmund", "Nordrhein-Westfalen", "44137"),
    ("Westenhellweg 1", "Dortmund", "Nordrhein-Westfalen", "44137"),
    ("Koenigstrasse 1", "Bochum", "Nordrhein-Westfalen", "44787"),
    ("Huestrasse 28", "Bochum", "Nordrhein-Westfalen", "44787"),
    ("Koenigstrasse 1", "Wuppertal", "Nordrhein-Westfalen", "42103"),
    ("Elberfelder Strasse 1", "Wuppertal", "Nordrhein-Westfalen", "42103"),
    ("Koenigstrasse 1", "Kiel", "Schleswig-Holstein", "24103"),
    ("Holstenstrasse 1", "Kiel", "Schleswig-Holstein", "24103"),
    ("Koenigstrasse 1", "Rostock", "Mecklenburg-Vorpommern", "18055"),
    ("Kroepeliner Strasse 1", "Rostock", "Mecklenburg-Vorpommern", "18055"),
    ("Koenigstrasse 1", "Magdeburg", "Sachsen-Anhalt", "39104"),
    ("Breiter Weg 1", "Magdeburg", "Sachsen-Anhalt", "39104"),
    ("Koenigstrasse 1", "Erfurt", "Thueringen", "99084"),
    ("Anger 1", "Erfurt", "Thueringen", "99084"),
    ("Koenigstrasse 1", "Saarbruecken", "Saarland", "66111"),
    ("Bahnhofstrasse 1", "Saarbruecken", "Saarland", "66111"),
]

AU_BILLING_NAMES = [
    ("James", "Smith"),
    ("Olivia", "Jones"),
    ("William", "Williams"),
    ("Charlotte", "Brown"),
    ("Jack", "Wilson"),
    ("Amelia", "Taylor"),
    ("Noah", "Anderson"),
    ("Isla", "Thomas"),
    ("Thomas", "Jackson"),
    ("Mia", "White"),
    ("Lucas", "Harris"),
    ("Grace", "Martin"),
    ("Henry", "Thompson"),
    ("Sophie", "Garcia"),
    ("Liam", "Martinez"),
    ("Emily", "Robinson"),
    ("Oliver", "Clark"),
    ("Chloe", "Rodriguez"),
    ("Ethan", "Lewis"),
    ("Ava", "Lee"),
    ("Mason", "Walker"),
    ("Ella", "Hall"),
    ("Alexander", "Allen"),
    ("Zoe", "Young"),
    ("Benjamin", "King"),
    ("Lily", "Wright"),
    ("Samuel", "Lopez"),
    ("Ruby", "Hill"),
    ("Daniel", "Scott"),
    ("Hannah", "Green"),
    ("Matthew", "Adams"),
    ("Sienna", "Baker"),
    ("Joshua", "Nelson"),
    ("Evie", "Carter"),
    ("Ryan", "Mitchell"),
    ("Harper", "Perez"),
    ("Nathan", "Roberts"),
    ("Matilda", "Turner"),
    ("Andrew", "Phillips"),
    ("Scarlett", "Campbell"),
]

AU_BILLING_STREETS = [
    ("1 Martin Place", "Sydney", "NSW", "2000"),
    ("200 George Street", "Sydney", "NSW", "2000"),
    ("100 Harris Street", "Sydney", "NSW", "2009"),
    ("477 Pitt Street", "Sydney", "NSW", "2000"),
    ("1 Collins Street", "Melbourne", "VIC", "3000"),
    ("120 Collins Street", "Melbourne", "VIC", "3000"),
    ("350 Bourke Street", "Melbourne", "VIC", "3000"),
    ("1 Queen Street", "Brisbane", "QLD", "4000"),
    ("123 Eagle Street", "Brisbane", "QLD", "4000"),
    ("1 Adelaide Terrace", "Perth", "WA", "6000"),
    ("100 St Georges Terrace", "Perth", "WA", "6000"),
    ("1 North Terrace", "Adelaide", "SA", "5000"),
    ("100 King William Street", "Adelaide", "SA", "5000"),
    ("1 London Circuit", "Canberra", "ACT", "2601"),
    ("50 Marcus Clarke Street", "Canberra", "ACT", "2601"),
    ("1 Hunter Street", "Newcastle", "NSW", "2300"),
    ("100 Hunter Street", "Newcastle", "NSW", "2300"),
    ("1 Smith Street", "Darwin", "NT", "0800"),
    ("50 Cavill Avenue", "Surfers Paradise", "QLD", "4217"),
    ("1 Macquarie Street", "Hobart", "TAS", "7000"),
    ("100 Elizabeth Street", "Hobart", "TAS", "7000"),
    ("1 Flinders Street", "Townsville", "QLD", "4810"),
    ("100 Flinders Street", "Townsville", "QLD", "4810"),
    ("1 Sturt Street", "Ballarat", "VIC", "3350"),
    ("100 Sturt Street", "Ballarat", "VIC", "3350"),
    ("1 Moorabool Street", "Geelong", "VIC", "3220"),
    ("100 Moorabool Street", "Geelong", "VIC", "3220"),
    ("1 Crown Street", "Wollongong", "NSW", "2500"),
    ("100 Crown Street", "Wollongong", "NSW", "2500"),
    ("1 Hay Street", "Subiaco", "WA", "6008"),
    ("100 Hay Street", "Subiaco", "WA", "6008"),
    ("1 Oxford Street", "Paddington", "NSW", "2021"),
    ("100 Oxford Street", "Paddington", "NSW", "2021"),
    ("1 Chapel Street", "South Yarra", "VIC", "3141"),
    ("100 Chapel Street", "South Yarra", "VIC", "3141"),
    ("1 James Street", "Fortitude Valley", "QLD", "4006"),
    ("100 James Street", "Fortitude Valley", "QLD", "4006"),
    ("1 Rundle Mall", "Adelaide", "SA", "5000"),
    ("100 Rundle Mall", "Adelaide", "SA", "5000"),
    ("1 Murray Street", "Perth", "WA", "6000"),
]